[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.28.0"
ci = "github"
installers = ["shell", "powershell", "npm"]
publish-jobs = ["npm"]
npm-scope = "@correctroadh"
npm-package = "toggl-cli"
github-releases-repo = "CorrectRoadH/toggl-cli"
targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  "x86_64-pc-windows-msvc",
]
pr-run-mode = "plan"
allow-dirty = ["ci"]
windows-archive = ".tar.gz"
unix-archive = ".tar.gz"

[dist.github-custom-runners]
"aarch64-apple-darwin" = "macos-latest"
"x86_64-apple-darwin" = "macos-latest"
"x86_64-unknown-linux-gnu" = "ubuntu-latest"
"x86_64-pc-windows-msvc" = "windows-latest"
